#!/bin/sh
# Following are example programs

# Compositer
# compton -CG --backend glx --vsync opengl-swc &

# Background picture
# feh --bg-center <image file>

# Run focus switcher server
# i3-alt-tab &
